# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-22 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=30)),
                ('abstract', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='pub date')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('open_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('date', models.DateTimeField(verbose_name='trading date')),
            ],
        ),
        migrations.CreateModel(
            name='Which_Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('name', models.CharField(default=' ', max_length=200)),
                ('change', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.AddField(
            model_name='stock_data',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ftsefinance.Which_Stock', unique_for_date='date'),
        ),
    ]
